language: rust
rust:
  - stable
  - beta

notifications:
  email: false


branches:
  only:
    - main

      #before_script:
# - rustup component add rustfmt
script:
  - cargo build
  - cargo test
#  - cargo fmt -- --check -
